name: Deploy develop branch

on:
  push:
    branches:
      - develop

permissions:
  contents: write

jobs:
  call-build-and-deploy:
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      ECR_NAME: poc-nuxt-frontend
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.POC_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.POC_AWS_SECRET_ACCESS_KEY }}
      SSH_KEY_MANIFEST: ${{ secrets.SSH_KEY_MANIFEST }}
